version: "3"
services:
  ui:
    image: reactmedicalsvcimg
    ports:
      - "9092:80"
    networks:
      - mynetb1
    depends_on:
      - doctorapp
      - patientapp

  doctorapp:
    image: doctorimg
    container_name: doctorapp
    ports:
      - "8001:8001"
    networks:
      - mynetb1
    environment:
      - MYSQL_HOST=mysqldb11
      - MYSQL_ROOT_PASSWORD=Root123$
      - MYSQL_PORT=3306
    depends_on:
      - mysqldb11

  patientapp:
    image: patientimg
    container_name: patientapp
    ports:
      - "8000:8000"
    networks:
      - mynetb1
    environment:
      - MYSQL_HOST=mysqldb12
      - MYSQL_ROOT_PASSWORD=Root123$
      - MYSQL_PORT=3306
    depends_on:
      - mysqldb12
      - doctorapp

  mysqldb11:
    image: mysql:latest
    ports:
      - "3308:3306"
    networks:
      - mynetb1
    environment:
      - MYSQL_ROOT_PASSWORD=Root123$
      - MYSQL_DATABASE=doctor_service_db

  mysqldb12:
    image: mysql:latest
    ports:
      - "3307:3306"
    networks:
      - mynetb1
    environment:
      - MYSQL_ROOT_PASSWORD=Root123$
      - MYSQL_DATABASE=patient_service_db

networks:
  mynetb1:
    driver: bridge


